; Lista de jogos disponíveis
; Formato: nome_do_arquivo.ini|Nome do Jogo|Gênero|Idioma

[Games]
game1 = super_mario_64.ini|Super Mario 64|Plataforma|Inglês
game2 = sonic_adventure.ini|Sonic Adventure|Aventura|Inglês
game3 = zelda_ocarina.ini|The Legend of Zelda|Aventura|Inglês
game4 = fifa_2024.ini|FIFA 2024|Esporte|Português
game5 = gta_san_andreas.ini|GTA San Andreas|Ação|Inglês
game6 = resident_evil_4.ini|Resident Evil 4|Terror|Espanhol
game7 = mario_kart.ini|Mario Kart|Corrida|Inglês
